### ISSUE TITLE
I am interest in this thing

### ISSUE THREAD

**Issue by lolisa** [Heather/heather.github.io#3]
one example I’ve been interested in recently is putting Big-O complexity into types
so proving some performance characteristics of algorithms
Well in Coq, the closest I have seen is a Framework for proving qsort's complexity.
Can you provide more description or provide a link?

**Comment by Heather** [comment]
@lolisa sure, here:
http://www.nuprl.org/documents/Constable/expressingcomputational.pdf
http://twanvl.nl/blog/agda/sorting

**Comment by lolisa** [comment]
Thx
